---
- name: Ensure that the directories exist
  file:
    path: '{{ item }}'
    state: directory
  loop:
  - '{{ ansible_env["HOME"] }}/bin'
  - '{{ mirror_directory }}'

- name: Drop all sneakernet binaries into user's ~/bin
  copy:
    src: '{{ bin_recovery_dir }}/{{ item }}'
    dest: '{{ ansible_env["HOME"] }}/bin/'
    mode: '0755'
  loop:
  - openshift-install
  - oc
  - helm
  - oc-mirror

- name: Drop all oc-mirror data
  copy:
    src: '{{ mirror_data_recovery_dir }}/'
    dest: '{{ mirror_directory }}'
