---
namespace: jharmison_redhat
name: oc_mirror_e2e
version: "0.1.0"
readme: README.md
authors:
- "James Harmison <jharmison@redhat.com>"
dependencies:
  ansible.posix: >=1.3.0,<2.0.0
  containers.podman: >=1.9.0,<2.0.0
  community.crypto: >=2.0.2,<3.0.0
  community.general: >=4.2.0,<5.0.0
license:
- BSD-2-Clause
tags:
- oc-mirror
- oc
- openshift
- kubernetes
- disconnected
- airgapped
repository: https://github.com/jharmison-redhat/oc-mirror-e2e
