---
- name: Ensure terraform setup is completed
  include_tasks: setup.yml

- name: Generate an OpenSSH keypair (it can be fake, as long as it exists)
  community.crypto.openssh_keypair:
    path: '{{ output_dir }}/{{ cluster_name }}_ed25519'
    type: ed25519
    comment: '{{ registry_admin.email }}'
  register: keypair

- name: Apply the terraform deployment
  include_tasks: terraform.yml
  vars:
      public_key: '{{ keypair.public_key }}'
      tf_task_state: absent
