---
- name: Move install-config into place
  copy:
    remote_src: true
    src: '{{ install_directory|dirname }}/install-config-orig.yaml'
    dest: '{{ install_directory }}/install-config.yaml'

- name: Create OpenShift manifests
  command: openshift-install create manifests
  environment:
    OPENSHIFT_INSTALL_RELEASE_IMAGE_OVERRIDE: '{{ registry_hostname }}/{{ toplevel_namespace }}/openshift/release:{{ mirrored_versions.stdout_lines|last }}-x86_64'
  args:
    chdir: '{{ install_directory }}'
