---
- name: Deprovision the infrastructure
  hosts: controller
  vars_files:
  - '{{ playbook_dir }}/vars/defaults.yml'
  tasks:
  - name: Destroy the terraform deployment
    include_role:
      name: provisioner
      tasks_from: destroy
