---
- name: Deprovision the infrastructure
  hosts: controller
  vars_files:
  - '{{ playbook_dir }}/vars/defaults.yml'
  tasks:
  - name: Destroy the terraform deployment
    include_role:
      name: provisioner
      tasks_from: terraform
    vars:
      tf_task_state: absent
      public_key: '{{ lookup("file", output_dir + "/" + cluster_name + "_ed25519.pub", errors="ignore")|default("") }}'
